# Generated by Django 2.0.1 on 2018-01-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tovar',
            old_name='id_tovar_fb',
            new_name='user',
        ),
    ]
